### ISSUE TITLE
Plugin is not working in Ventura 13.2.1

### ISSUE THREAD

**Issue by tovolkmar** [wwwjfy/GMailinator#7]
Hi,
I currently have a problem to get the plugin running in Ventura 13.2.1.

I tried the following steps:
- Downloaded the current Master Branch
- Build the project in Xcode
- Signed the bundle in /tmp and copied it to ~/Library/Mail/
- Allowed the plugin in system settings via spctl
- Enabled the plugins in Apple Mail via defaults write com.apple.mail EnableBundles -bool true

Any Ideas what I'm missing here, or where the problem could be?

Best regards,
Tobias

**Comment by wwwjfy** [comment]
Please be specific on the problem, like screenshot or error message.

**Comment by rterbush** [comment]
I can confirm that this does run after Xcode build on 13.2.1.

I did change deployment target to 13.0 and jumped through hoops to get local code signing to work. After running spctl, the plugin works as advertised. I don't think the change in target was needed to get this to run, but perhaps worth a try and as the author writes, need to know specifically how it is failing to be of further help.

**Comment by tovolkmar** [comment]
Sorry for the late reply.
I'd like to be specific as possible, but unfortunately I get no error messages. All steps run without error. From building the project, signing it and allowing the plugin via spctl. Everything is running without any error. But unfortunately I am not able to see the pluging in Mail in the settings. Also restarting doesn't help.
Will try to change the deployment target, maybe that helps.

Best regards,
Tobias

**Comment by wwwjfy** [comment]
If this is the case, I guess either plugin feature is not enabled for Mail, or the package is put in a wrong path.
You should have this file `~/Library/Mail/Bundles/GMailinator.mailbundle/Contents/Info.plist`

**Comment by tovolkmar** [comment]
I can see if the plugin feature is enabled when I have the "Manage Plugins" button under Settings -> General, correct?
The package is in the correct path. I double checked that.

**Comment by wwwjfy** [comment]
I have no clue then. All the problems I met before were I couldn't activated it, but could always see it there.

Maybe logs in Console can give some hint.

**Comment by erikw** [comment]
Hey, thanks for providing this fork! I'm much interested in getting Gmail-like keyboard bindings for Apple Mail.

Currently I found the current README instructions a bit unclear, in the case that one is on macOS Ventura -- is it enough to download the GitHub release zip file, or does one always need to build the project oneself locally on Ventura and later?

I downloaded the zip file, placed it where it should be, and enabled it in Mapl.app preferences under the General tab. After restarting Mail.app I see this:

<img width="136" alt="Screenshot 2023-05-22 at 21 37 43" src="https://github.com/wwwjfy/GMailinator/assets/175286/15dff8a8-5d74-49fd-b95e-19bc172cc279">

I guess this is due to the code signing mentioned under "Allow usage in Big Sur" in the README. This would then imply that on >= Ventura one should always build the project self. In this case, the section named "How to install (Mojave onwards)" is confusing as it says one can download the zip bundle (which was the case before Ventura) :)

What identity should one put in "Replace with the identity"?

Anyways, what would be needed to make this easier to install? 
Let's think big! What would it take to make this as easy as `$ brew install gmailinator`?
* Automated code signing?
* Hosting?

:) 

**Edit.**
Using the `install.sh` from the fork https://github.com/jasoncodes/GMailinator/blob/master/install.sh (that is based on this fork) I got it to work!

(basically it's just to run `xcodebuild` in the git repo)

**Comment by wwwjfy** [comment]
hmm, I see this script doesn't do anything different. Running xcodebuild in terminal and building it in Xcode should have same binary.

I stopped uploading zip file to release some time ago because I see it's trivial for users to do if they already need to do code sign and spctl.

The script is actually a good idea. Going with homebrew I'm not sure, something to explore~

**Comment by milkrisc-v** [comment]
After changing the build target to Ventura 13.4, it works now. 

``` diff
diff --git a/GMailinator.xcodeproj/project.pbxproj b/GMailinator.xcodeproj/project.pbxproj
index c917313..fde2efc 100644
--- a/GMailinator.xcodeproj/project.pbxproj
+++ b/GMailinator.xcodeproj/project.pbxproj
@@ -262,7 +262,7 @@
 				GCC_WARN_UNINITIALIZED_AUTOS = YES;
 				GCC_WARN_UNUSED_FUNCTION = YES;
 				GCC_WARN_UNUSED_VARIABLE = YES;
-				MACOSX_DEPLOYMENT_TARGET = 10.9;
+				MACOSX_DEPLOYMENT_TARGET = 13.3;
 				ONLY_ACTIVE_ARCH = YES;
 				SDKROOT = macosx;
 			};
@@ -307,7 +307,7 @@
 				GCC_WARN_UNINITIALIZED_AUTOS = YES;
 				GCC_WARN_UNUSED_FUNCTION = YES;
 				GCC_WARN_UNUSED_VARIABLE = YES;
-				MACOSX_DEPLOYMENT_TARGET = 10.9;
+				MACOSX_DEPLOYMENT_TARGET = 13.3;
 				SDKROOT = macosx;
 			};
 			name = Release;
@@ -316,6 +316,9 @@
 			isa = XCBuildConfiguration;
 			buildSettings = {
 				CLANG_ENABLE_OBJC_ARC = YES;
+				CODE_SIGN_IDENTITY = "Apple Development";
+				"CODE_SIGN_IDENTITY[sdk=macosx*]" = "-";
+				CODE_SIGN_STYLE = Automatic;
 				COMBINE_HIDPI_IMAGES = YES;
 				DEAD_CODE_STRIPPING = YES;
 				DEVELOPMENT_TEAM = "";
@@ -323,11 +326,12 @@
 				GCC_PREFIX_HEADER = "GMailinator/GMailinator-Prefix.pch";
 				INFOPLIST_FILE = GMailinator/Info.plist;
 				INSTALL_PATH = "$(HOME)/Library/Mail/Bundles";
-				MACOSX_DEPLOYMENT_TARGET = "$(RECOMMENDED_MACOSX_DEPLOYMENT_TARGET)";
+				MACOSX_DEPLOYMENT_TARGET = 13.4;
 				MARKETING_VERSION = 1.0.5;
 				ONLY_ACTIVE_ARCH = NO;
 				PRODUCT_BUNDLE_IDENTIFIER = "com.nompute.gmailinator.${PRODUCT_NAME:rfc1034identifier}";
 				PRODUCT_NAME = GMailinator;
+				PROVISIONING_PROFILE_SPECIFIER = "";
 				WRAPPER_EXTENSION = mailbundle;
 			};
 			name = Debug;
@@ -336,6 +340,9 @@
 			isa = XCBuildConfiguration;
 			buildSettings = {
 				CLANG_ENABLE_OBJC_ARC = YES;
+				CODE_SIGN_IDENTITY = "Apple Development";
+				"CODE_SIGN_IDENTITY[sdk=macosx*]" = "-";
+				CODE_SIGN_STYLE = Automatic;
 				COMBINE_HIDPI_IMAGES = YES;
 				DEAD_CODE_STRIPPING = YES;
 				DEVELOPMENT_TEAM = "";
@@ -343,10 +350,11 @@
 				GCC_PREFIX_HEADER = "GMailinator/GMailinator-Prefix.pch";
 				INFOPLIST_FILE = GMailinator/Info.plist;
 				INSTALL_PATH = "$(HOME)/Library/Mail/Bundles";
-				MACOSX_DEPLOYMENT_TARGET = "$(RECOMMENDED_MACOSX_DEPLOYMENT_TARGET)";
+				MACOSX_DEPLOYMENT_TARGET = 13.4;
 				MARKETING_VERSION = 1.0.5;
 				PRODUCT_BUNDLE_IDENTIFIER = "com.nompute.gmailinator.${PRODUCT_NAME:rfc1034identifier}";
 				PRODUCT_NAME = GMailinator;
+				PROVISIONING_PROFILE_SPECIFIER = "";
 				WRAPPER_EXTENSION = mailbundle;
 			};
 			name = Release;

```

**Comment by wwwjfy** [comment]
If you build directly (command-B), it'll use Debug config, which is set to be `RECOMMENDED_MACOSX_DEPLOYMENT_TARGET`, i.e. minimal version supported by your xcode.

Your change is about config Release, which is not used.

Let me update that to `RECOMMENDED_MACOSX_DEPLOYMENT_TARGET` as well.
